#!/bin/bash

# Set timezone
if test -f "/usr/share/zoneinfo/${TZ}"; then
    if test -f "/etc/localtime"; then
        rm /etc/localtime
    fi
    ln "/usr/share/zoneinfo/${TZ}" /etc/localtime
fi

# Start the mux
odr-dabmux "${1}"
