name: docker-publish

on:
  release:
    types: [published]
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get last tag
        run: |
          echo "lastTag=$(git tag --list | head --lines=1)" >> "$GITHUB_ENV"
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dabmux:latest,${{ secrets.DOCKERHUB_USERNAME }}/dabmux:${{ env.lastTag }}
